# Generated by Django 5.2.15 on 2026-07-04 10:16

import uuid

import django.contrib.postgres.indexes
from django.db import migrations, models

import apps.basedata.models


class Migration(migrations.Migration):

    dependencies = [
        ("basedata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigationCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "investigation categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LookupValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(db_index=True, max_length=64)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["category", "sort_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("category", "code"), name="uniq_lookup_category_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(default="Ethiopian", max_length=64)),
                (
                    "national_id_no",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("addresses", models.JSONField(blank=True, default=list)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.basedata.models.person_photo_path,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["person_no"],
                "indexes": [
                    models.Index(
                        fields=["last_name", "first_name"],
                        name="basedata_pe_last_na_023b0e_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["addresses"], name="basedata_pe_address_54a3cd_gin"
                    ),
                ],
            },
        ),
    ]
