# Generated by Django 5.2.15 on 2026-07-04 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_timeslot"),
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="registration.clearanceapplication",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.station",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to="appointments.station",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.timeslot",
            ),
        ),
        migrations.AddConstraint(
            model_name="timeslot",
            constraint=models.UniqueConstraint(
                fields=("station", "start_time", "end_time"),
                name="uniq_slot_station_window",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["station", "date", "status"],
                name="appointment_station_682816_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "booked")),
                fields=("slot", "date", "phone"),
                name="uniq_active_booking_per_phone",
            ),
        ),
    ]
