# Generated by Django 5.2.15 on 2026-07-04 16:04

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basedata", "0003_person_no_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClearanceApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("purpose", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("paid", "Paid"),
                            ("biometrics_captured", "Biometrics captured"),
                            ("in_review", "In review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("certificate_issued", "Certificate issued"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                (
                    "id_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.registration.models.id_document_path,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clearance_applications",
                        to="basedata.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="registratio_status_cfe225_idx",
                    )
                ],
            },
        ),
    ]
