# Generated by Django 5.2.15 on 2026-07-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_tracking_no_sequence"),
    ]

    operations = [
        migrations.AddField(
            model_name="clearanceapplication",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
