# Generated by Django 5.2.15 on 2026-07-04 20:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apimgmt", "0001_initial"),
        ("clearance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verification_no_attempted", models.CharField(max_length=40)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("portal", "Public portal"),
                            ("qr", "QR scan"),
                            ("api", "Institutional API"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        max_length=8,
                    ),
                ),
                ("verifier_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "api_credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_events",
                        to="apimgmt.apicredential",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verification_events",
                        to="clearance.certificate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["channel", "created_at"],
                        name="verificatio_channel_5722ea_idx",
                    )
                ],
            },
        ),
    ]
