# Generated by Django 5.2.15 on 2026-07-04 20:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.clearance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basedata", "0003_person_no_sequence"),
        ("registration", "0002_tracking_no_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "verification_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("qr_payload", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.clearance.models.certificate_pdf_path,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("valid", "Valid"), ("revoked", "Revoked")],
                        default="valid",
                        max_length=8,
                    ),
                ),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificate",
                        to="registration.clearanceapplication",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="basedata.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["verification_no"],
                        name="clearance_c_verific_9c0933_idx",
                    )
                ],
            },
        ),
    ]
