# Generated by Django 5.2.15 on 2026-07-04 10:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basedata", "0003_person_no_sequence"),
        ("enrollment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("TP-TP", "Tenprint vs tenprint"),
                            ("TP-LT", "Tenprint vs latents"),
                            ("LT-TP", "Latent vs tenprints"),
                            ("LT-LT", "Latent vs latents"),
                            ("FACE-1N", "Face 1:N"),
                            ("VERIFY-1_1", "Verify 1:1"),
                            ("DEDUP", "Enrollment deduplication"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                (
                    "probe_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dedup_jobs",
                        to="enrollment.enrollment",
                    ),
                ),
                (
                    "probe_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_jobs",
                        to="enrollment.biometricrecord",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MatchCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.FloatField()),
                ("rank", models.PositiveSmallIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("undecided", "Undecided"),
                            ("hit", "Hit"),
                            ("no_hit", "No hit"),
                        ],
                        default="undecided",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_candidates",
                        to="basedata.person",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="match_candidates",
                        to="enrollment.biometricrecord",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidate_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="matching.matchjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="matchjob",
            index=models.Index(
                fields=["status", "created_at"], name="matching_ma_status_e5c8d1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="matchcandidate",
            constraint=models.UniqueConstraint(
                fields=("job", "rank"), name="uniq_candidate_job_rank"
            ),
        ),
    ]
