# Generated by Django 5.2.15 on 2026-07-04 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basedata", "0003_person_no_sequence"),
        ("enrollment", "0001_initial"),
        ("investigation", "0001_initial"),
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="matchcandidate",
            name="latent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="candidate_hits",
                to="investigation.latentprint",
            ),
        ),
        migrations.AddField(
            model_name="matchjob",
            name="probe_latent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_jobs",
                to="investigation.latentprint",
            ),
        ),
        migrations.AlterField(
            model_name="matchcandidate",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_candidates",
                to="basedata.person",
            ),
        ),
        migrations.AlterField(
            model_name="matchcandidate",
            name="record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_candidates",
                to="enrollment.biometricrecord",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchcandidate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("record__isnull", False),
                    ("latent__isnull", False),
                    _connector="OR",
                ),
                name="candidate_has_record_or_latent",
            ),
        ),
    ]
