# Generated by Django 5.2.15 on 2026-07-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_matchcandidate_latent_matchjob_probe_latent_and_more"),
        ("pis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchjob",
            name="probe_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="match_jobs",
                to="pis.photoprobe",
            ),
        ),
    ]
