# Generated by Django 5.2.15 on 2026-07-04 10:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.investigation.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("basedata", "0003_person_no_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("archived", "Archived"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cases",
                        to="basedata.investigationcategory",
                    ),
                ),
                (
                    "lead_investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.investigation.models.evidence_file_path
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("collected_by", models.CharField(max_length=150)),
                ("collected_at", models.DateTimeField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="investigation.case",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="LatentPrint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modality",
                    models.CharField(
                        choices=[("finger", "Fingerprint"), ("palm", "Palmprint")],
                        max_length=8,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to=apps.investigation.models.latent_image_path
                    ),
                ),
                (
                    "enhanced_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.investigation.models.latent_enhanced_path,
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("minutiae", models.JSONField(blank=True, default=list)),
                ("editor_history", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="latents",
                        to="investigation.case",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_latents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["case", "modality"],
                        name="investigati_case_id_fc1027_idx",
                    )
                ],
            },
        ),
    ]
