# Generated by Django 5.2.15 on 2026-07-04 10:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.enrollment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("basedata", "0003_person_no_sequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("finger", "Fingerprint"),
                            ("palm", "Palmprint"),
                            ("face", "Face"),
                        ],
                        max_length=8,
                    ),
                ),
                ("position", models.CharField(max_length=16)),
                (
                    "image",
                    models.FileField(
                        upload_to=apps.enrollment.models.biometric_image_path
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                ("quality_score", models.PositiveSmallIntegerField()),
                ("accepted", models.BooleanField()),
                ("nist_meta", models.JSONField(blank=True, default=dict)),
                (
                    "captured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="captured_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="biometric_records",
                        to="basedata.person",
                    ),
                ),
            ],
            options={
                "ordering": ["modality", "position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BiometricTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("engine", models.CharField(max_length=32)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("template_bytes", models.BinaryField()),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template",
                        to="enrollment.biometricrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="basedata.person",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="appointments.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="biometricrecord",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="enrollment.enrollment",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricrecord",
            index=models.Index(
                fields=["person", "modality"], name="enrollment__person__e92912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricrecord",
            index=models.Index(
                fields=["enrollment", "modality", "position"],
                name="enrollment__enrollm_972d0e_idx",
            ),
        ),
    ]
